//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AN.Core.Resources.UI.WebSite {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WebsiteResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebsiteResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AN.Core.Resources.UI.WebSite.WebsiteResource", typeof(WebsiteResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AwroNore quote.
        /// </summary>
        public static string AwroNoreQuote {
            get {
                return ResourceManager.GetString("AwroNoreQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear customer.
        /// </summary>
        public static string DearCustomer {
            get {
                return ResourceManager.GetString("DearCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please come 30 minutes in advance.
        /// </summary>
        public static string Msg_PleaseCome30MinEarlier {
            get {
                return ResourceManager.GetString("Msg_PleaseCome30MinEarlier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register patient form.
        /// </summary>
        public static string Msg_RegisterPatientForm {
            get {
                return ResourceManager.GetString("Msg_RegisterPatientForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your appointment is booked successfully!.
        /// </summary>
        public static string Msg_YourTurnBookedSuccessfuly {
            get {
                return ResourceManager.GetString("Msg_YourTurnBookedSuccessfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polyclinic details.
        /// </summary>
        public static string PolyclinicDetails {
            get {
                return ResourceManager.GetString("PolyclinicDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polyclinic name.
        /// </summary>
        public static string PolyclinicName {
            get {
                return ResourceManager.GetString("PolyclinicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polyclinic register form.
        /// </summary>
        public static string PolyclinicRegisterForm {
            get {
                return ResourceManager.GetString("PolyclinicRegisterForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register patient.
        /// </summary>
        public static string RegisterPatient {
            get {
                return ResourceManager.GetString("RegisterPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View and print receipt.
        /// </summary>
        public static string ViewAndPrintReceipt {
            get {
                return ResourceManager.GetString("ViewAndPrintReceipt", resourceCulture);
            }
        }
    }
}
