//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AN.Core.Resources.EntitiesResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AN.Core.Resources.EntitiesResources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to do this action.
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to According to change doctor schedule.
        /// </summary>
        public static string AccordingToChangeDoctorSchedule {
            get {
                return ResourceManager.GetString("AccordingToChangeDoctorSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to According to doctor absense.
        /// </summary>
        public static string AccordingToDoctorAbsense {
            get {
                return ResourceManager.GetString("AccordingToDoctorAbsense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action done succesfully.
        /// </summary>
        public static string ActionDoneSuccesfully {
            get {
                return ResourceManager.GetString("ActionDoneSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while adding item.
        /// </summary>
        public static string AnErrorOccuredWhileAddingItem {
            get {
                return ResourceManager.GetString("AnErrorOccuredWhileAddingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while delete item.
        /// </summary>
        public static string AnErrorOccuredWhileDeleteItem {
            get {
                return ResourceManager.GetString("AnErrorOccuredWhileDeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while update item.
        /// </summary>
        public static string AnErrorOccuredWhileUpdateItem {
            get {
                return ResourceManager.GetString("AnErrorOccuredWhileUpdateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your appointment has been done successfully, kindly rate your visit!.
        /// </summary>
        public static string AppointmentDoneNotificationBody {
            get {
                return ResourceManager.GetString("AppointmentDoneNotificationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Done.
        /// </summary>
        public static string AppointmentDoneNotificationTitle {
            get {
                return ResourceManager.GetString("AppointmentDoneNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete appointment?.
        /// </summary>
        public static string AreYouSureToDeleteTurn {
            get {
                return ResourceManager.GetString("AreYouSureToDeleteTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity is smaller than requested.
        /// </summary>
        public static string CapacityIsSmallerThanRequested {
            get {
                return ResourceManager.GetString("CapacityIsSmallerThanRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center has pending appointments .
        /// </summary>
        public static string CenterHasPendingTurns {
            get {
                return ResourceManager.GetString("CenterHasPendingTurns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete current user exception.
        /// </summary>
        public static string DeleteCurrentUserException {
            get {
                return ResourceManager.GetString("DeleteCurrentUserException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The doctor has already been assigned to the polyclinic .
        /// </summary>
        public static string DoctorAssignedToPolyclinicAlready {
            get {
                return ResourceManager.GetString("DoctorAssignedToPolyclinicAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The doctor has pending appointments.
        /// </summary>
        public static string DoctorHasPendingTurns {
            get {
                return ResourceManager.GetString("DoctorHasPendingTurns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor has pending appointments, you cannot remove his role.
        /// </summary>
        public static string DoctorHasPendingTurnsYouCannotRemoveHisRole {
            get {
                return ResourceManager.GetString("DoctorHasPendingTurnsYouCannotRemoveHisRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor is not active.
        /// </summary>
        public static string DoctorIsNotActive {
            get {
                return ResourceManager.GetString("DoctorIsNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor is not available.
        /// </summary>
        public static string DoctorNotAvailable {
            get {
                return ResourceManager.GetString("DoctorNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor not found.
        /// </summary>
        public static string DoctorNotFound {
            get {
                return ResourceManager.GetString("DoctorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor not present in polyclinic.
        /// </summary>
        public static string DoctorNotPresentInPolyclinic {
            get {
                return ResourceManager.GetString("DoctorNotPresentInPolyclinic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is duplicate.
        /// </summary>
        public static string EmailIsDuplicate {
            get {
                return ResourceManager.GetString("EmailIsDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not valid.
        /// </summary>
        public static string EmailIsNotValid {
            get {
                return ResourceManager.GetString("EmailIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty time period not valid.
        /// </summary>
        public static string EmptyTimePeriodNotValid {
            get {
                return ResourceManager.GetString("EmptyTimePeriodNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity not found exception.
        /// </summary>
        public static string EntityNotFoundException {
            get {
                return ResourceManager.GetString("EntityNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured when check version pattern.
        /// </summary>
        public static string ErrorOccuredWhenCheckVersionPattern {
            get {
                return ResourceManager.GetString("ErrorOccuredWhenCheckVersionPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while assign role.
        /// </summary>
        public static string ErrorOccuredWhileAssignRole {
            get {
                return ResourceManager.GetString("ErrorOccuredWhileAssignRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while done action.
        /// </summary>
        public static string ErrorOccuredWhileDoneAction {
            get {
                return ResourceManager.GetString("ErrorOccuredWhileDoneAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while final book turn.
        /// </summary>
        public static string ErrorOccuredWhileFinalBookTurn {
            get {
                return ResourceManager.GetString("ErrorOccuredWhileFinalBookTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while unassigning role.
        /// </summary>
        public static string ErrorWhileUnAssignRole {
            get {
                return ResourceManager.GetString("ErrorWhileUnAssignRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evening shift end time is not valid.
        /// </summary>
        public static string EveningShiftEndNotValid {
            get {
                return ResourceManager.GetString("EveningShiftEndNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evening shit start time is not valid.
        /// </summary>
        public static string EveningShitStartNotValid {
            get {
                return ResourceManager.GetString("EveningShitStartNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File exists with this key.
        /// </summary>
        public static string FileExistWithThisKey {
            get {
                return ResourceManager.GetString("FileExistWithThisKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is required.
        /// </summary>
        public static string FileIsRequired {
            get {
                return ResourceManager.GetString("FileIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has been transmitted.
        /// </summary>
        public static string HasBeenTransmitted {
            get {
                return ResourceManager.GetString("HasBeenTransmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has canceled.
        /// </summary>
        public static string HasCanceled {
            get {
                return ResourceManager.GetString("HasCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has done.
        /// </summary>
        public static string HasDone {
            get {
                return ResourceManager.GetString("HasDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have appointment with another doctor in the selected time.
        /// </summary>
        public static string HaveAppointmentWithAnotherDoctorAtTime {
            get {
                return ResourceManager.GetString("HaveAppointmentWithAnotherDoctorAtTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have an appointment, please come at time.
        /// </summary>
        public static string HaveTurnPleaseComeAtTime {
            get {
                return ResourceManager.GetString("HaveTurnPleaseComeAtTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have appointments.
        /// </summary>
        public static string HaveTurns {
            get {
                return ResourceManager.GetString("HaveTurns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health service has a pending appointment.
        /// </summary>
        public static string HealthServiceHasPendingTurn {
            get {
                return ResourceManager.GetString("HealthServiceHasPendingTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospital not found.
        /// </summary>
        public static string HospitalNotFound {
            get {
                return ResourceManager.GetString("HospitalNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In date.
        /// </summary>
        public static string InDate {
            get {
                return ResourceManager.GetString("InDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In polyclinic.
        /// </summary>
        public static string InPolyclinic {
            get {
                return ResourceManager.GetString("InPolyclinic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item added successFully.
        /// </summary>
        public static string ItemAddedSuccessFully {
            get {
                return ResourceManager.GetString("ItemAddedSuccessFully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item deleted  successFully.
        /// </summary>
        public static string ItemDeletedSuccessFully {
            get {
                return ResourceManager.GetString("ItemDeletedSuccessFully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item not found.
        /// </summary>
        public static string ItemNotFound {
            get {
                return ResourceManager.GetString("ItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item updated successFully.
        /// </summary>
        public static string ItemUpdatedSuccessFully {
            get {
                return ResourceManager.GetString("ItemUpdatedSuccessFully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum allowed size.
        /// </summary>
        public static string MaxAllowedSize {
            get {
                return ResourceManager.GetString("MaxAllowedSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message has been sent already.
        /// </summary>
        public static string MessageHasSentAlready {
            get {
                return ResourceManager.GetString("MessageHasSentAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile has turn for date.
        /// </summary>
        public static string MobileHasTurnForDate {
            get {
                return ResourceManager.GetString("MobileHasTurnForDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile is not valid.
        /// </summary>
        public static string MobileIsNotValid {
            get {
                return ResourceManager.GetString("MobileIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile number duplicate.
        /// </summary>
        public static string MobileNumberDuplicate {
            get {
                return ResourceManager.GetString("MobileNumberDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morning shift end not valid.
        /// </summary>
        public static string MorningShiftEndNotValid {
            get {
                return ResourceManager.GetString("MorningShiftEndNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morning shift start not valid.
        /// </summary>
        public static string MorningShiftStartNotValid {
            get {
                return ResourceManager.GetString("MorningShiftStartNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied.
        /// </summary>
        public static string Msg_AccessDenied {
            get {
                return ResourceManager.GetString("Msg_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied 403.
        /// </summary>
        public static string Msg_AccessDenied403 {
            get {
                return ResourceManager.GetString("Msg_AccessDenied403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajax request aborted.
        /// </summary>
        public static string Msg_AjaxRequestAborted {
            get {
                return ResourceManager.GetString("Msg_AjaxRequestAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection error.
        /// </summary>
        public static string Msg_ConnectionError {
            get {
                return ResourceManager.GetString("Msg_ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal server error 500.
        /// </summary>
        public static string Msg_InternalServerError500 {
            get {
                return ResourceManager.GetString("Msg_InternalServerError500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested JSON parse failed.
        /// </summary>
        public static string Msg_RequestedJSONParseFailed {
            get {
                return ResourceManager.GetString("Msg_RequestedJSONParseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested page not found 404.
        /// </summary>
        public static string Msg_RequestedPageNotFound404 {
            get {
                return ResourceManager.GetString("Msg_RequestedPageNotFound404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time out error.
        /// </summary>
        public static string Msg_TimeOutError {
            get {
                return ResourceManager.GetString("Msg_TimeOutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No doctor is selected.
        /// </summary>
        public static string NoDoctorSelected {
            get {
                return ResourceManager.GetString("NoDoctorSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No health service is selected.
        /// </summary>
        public static string NoHealthServiceSelected {
            get {
                return ResourceManager.GetString("NoHealthServiceSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Item Found.
        /// </summary>
        public static string NoItemFound {
            get {
                return ResourceManager.GetString("NoItemFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No picture is selected.
        /// </summary>
        public static string NoPictureSelected {
            get {
                return ResourceManager.GetString("NoPictureSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No speciality selected.
        /// </summary>
        public static string NoSpecialitySelected {
            get {
                return ResourceManager.GetString("NoSpecialitySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found valid schedule exception.
        /// </summary>
        public static string NotFoundValidScheduleException {
            get {
                return ResourceManager.GetString("NotFoundValidScheduleException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online appointments queue number.
        /// </summary>
        public static string OnlineTurnsQueueNumber {
            get {
                return ResourceManager.GetString("OnlineTurnsQueueNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Not Found.
        /// </summary>
        public static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password assigned successfully.
        /// </summary>
        public static string PasswordAssignedSuccessfully {
            get {
                return ResourceManager.GetString("PasswordAssignedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully.
        /// </summary>
        public static string PasswordChangedSuccessfully {
            get {
                return ResourceManager.GetString("PasswordChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be 6 digits.
        /// </summary>
        public static string PasswordMustBe6Digits {
            get {
                return ResourceManager.GetString("PasswordMustBe6Digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords did not match.
        /// </summary>
        public static string PasswordsNotSame {
            get {
                return ResourceManager.GetString("PasswordsNotSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient has no record.
        /// </summary>
        public static string PatientHasNoRecord {
            get {
                return ResourceManager.GetString("PatientHasNoRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Has No Treatments.
        /// </summary>
        public static string PatientHasNoTreatments {
            get {
                return ResourceManager.GetString("PatientHasNoTreatments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient has pending appointments.
        /// </summary>
        public static string PatientHasPendingTurns {
            get {
                return ResourceManager.GetString("PatientHasPendingTurns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending appointments exist in date.
        /// </summary>
        public static string PendingTurnsExistInDate {
            get {
                return ResourceManager.GetString("PendingTurnsExistInDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        public static string Person {
            get {
                return ResourceManager.GetString("Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person with this mobile number already exists.
        /// </summary>
        public static string PersonMobileDuplicate {
            get {
                return ResourceManager.GetString("PersonMobileDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter all requested data.
        /// </summary>
        public static string PleaseEnterAllRequestedData {
            get {
                return ResourceManager.GetString("PleaseEnterAllRequestedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter email.
        /// </summary>
        public static string PleaseEnterEmail {
            get {
                return ResourceManager.GetString("PleaseEnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter file key.
        /// </summary>
        public static string PleaseEnterFileKey {
            get {
                return ResourceManager.GetString("PleaseEnterFileKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter mobile.
        /// </summary>
        public static string PleaseEnterMobile {
            get {
                return ResourceManager.GetString("PleaseEnterMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid captcha.
        /// </summary>
        public static string PleaseEnterValidCaptcha {
            get {
                return ResourceManager.GetString("PleaseEnterValidCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid date.
        /// </summary>
        public static string PleaseEnterValidDate {
            get {
                return ResourceManager.GetString("PleaseEnterValidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select file with specified format.
        /// </summary>
        public static string PleaseSelectFileWithSpecifiedFormat {
            get {
                return ResourceManager.GetString("PleaseSelectFileWithSpecifiedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a picture with specefied format.
        /// </summary>
        public static string PleaseSelectPicWithSpecefiedFormat {
            get {
                return ResourceManager.GetString("PleaseSelectPicWithSpecefiedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter start end date time.
        /// </summary>
        public static string PlsEnterStartEndDateTime {
            get {
                return ResourceManager.GetString("PlsEnterStartEndDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polyclinic does not have health service.
        /// </summary>
        public static string PolyclinicDontHasHelathService {
            get {
                return ResourceManager.GetString("PolyclinicDontHasHelathService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polyclinic has pending appointments.
        /// </summary>
        public static string PolyclinicHasPendingTurns {
            get {
                return ResourceManager.GetString("PolyclinicHasPendingTurns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polyclinic not found.
        /// </summary>
        public static string PolyclinicNotFound {
            get {
                return ResourceManager.GetString("PolyclinicNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescription is done before.
        /// </summary>
        public static string PrescriptionIsDoneBefore {
            get {
                return ResourceManager.GetString("PrescriptionIsDoneBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescription not found.
        /// </summary>
        public static string PrescriptionNotFound {
            get {
                return ResourceManager.GetString("PrescriptionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reception.
        /// </summary>
        public static string Reception {
            get {
                return ResourceManager.GetString("Reception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover password.
        /// </summary>
        public static string RecoverPassword {
            get {
                return ResourceManager.GetString("RecoverPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve confirmation.
        /// </summary>
        public static string ReserveConfirmation {
            get {
                return ResourceManager.GetString("ReserveConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved appointments list.
        /// </summary>
        public static string ReservedTurnsList {
            get {
                return ResourceManager.GetString("ReservedTurnsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules and regulations.
        /// </summary>
        public static string RulesAndRegulations {
            get {
                return ResourceManager.GetString("RulesAndRegulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule deactivated successfully.
        /// </summary>
        public static string ScheduleDeActiveSuccessfully {
            get {
                return ResourceManager.GetString("ScheduleDeActiveSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule for disabled day exception.
        /// </summary>
        public static string ScheduleForDisabledDayException {
            get {
                return ResourceManager.GetString("ScheduleForDisabledDayException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule for not working hours exception.
        /// </summary>
        public static string ScheduleForNotWorkingHoursException {
            get {
                return ResourceManager.GetString("ScheduleForNotWorkingHoursException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule for past exception.
        /// </summary>
        public static string ScheduleForPastException {
            get {
                return ResourceManager.GetString("ScheduleForPastException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule for vocation day exception.
        /// </summary>
        public static string ScheduleForVocationDayException {
            get {
                return ResourceManager.GetString("ScheduleForVocationDayException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule has interferes with previews.
        /// </summary>
        public static string ScheduleHasInterferesWithPreviews {
            get {
                return ResourceManager.GetString("ScheduleHasInterferesWithPreviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule not specified for date.
        /// </summary>
        public static string ScheduleNotSpecifiedForDate {
            get {
                return ResourceManager.GetString("ScheduleNotSpecifiedForDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule outside bound exception.
        /// </summary>
        public static string ScheduleOutsideBoundException {
            get {
                return ResourceManager.GetString("ScheduleOutsideBoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end date must be greater than the start date.
        /// </summary>
        public static string ScheduleStartMustSmallerThanEnd {
            get {
                return ResourceManager.GetString("ScheduleStartMustSmallerThanEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule start not valid for BHR.
        /// </summary>
        public static string ScheduleStartNotValidForBHR {
            get {
                return ResourceManager.GetString("ScheduleStartNotValidForBHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule start smaller than doctor turning start.
        /// </summary>
        public static string ScheduleStartSmallerThanDoctorTurningStart {
            get {
                return ResourceManager.GetString("ScheduleStartSmallerThanDoctorTurningStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send picture with this format.
        /// </summary>
        public static string SendPicWithThisFormats {
            get {
                return ResourceManager.GetString("SendPicWithThisFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Something went wrong..
        /// </summary>
        public static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting and end time not valid.
        /// </summary>
        public static string StartingAndEndTimeNotValid {
            get {
                return ResourceManager.GetString("StartingAndEndTimeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System vacation day exception.
        /// </summary>
        public static string SystemVocationDayException {
            get {
                return ResourceManager.GetString("SystemVocationDayException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To date.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow you.
        /// </summary>
        public static string TommorwYou {
            get {
                return ResourceManager.GetString("TommorwYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow you in.
        /// </summary>
        public static string TommowYouIn {
            get {
                return ResourceManager.GetString("TommowYouIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment booked finally.
        /// </summary>
        public static string TurnBookedFinally {
            get {
                return ResourceManager.GetString("TurnBookedFinally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment is in progress now.
        /// </summary>
        public static string TurnIsInProgressNow {
            get {
                return ResourceManager.GetString("TurnIsInProgressNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment reserved successfully.
        /// </summary>
        public static string TurnReservedSuccessfully {
            get {
                return ResourceManager.GetString("TurnReservedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment time passed.
        /// </summary>
        public static string TurnTimePassed {
            get {
                return ResourceManager.GetString("TurnTimePassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unassign doctor with pending appointments exception.
        /// </summary>
        public static string UnAssignDoctorWithPendingAppointmentsException {
            get {
                return ResourceManager.GetString("UnAssignDoctorWithPendingAppointmentsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error occurred in server please contact admin.
        /// </summary>
        public static string UnKnownErrorOccuredInServerPlsContactAdmin {
            get {
                return ResourceManager.GetString("UnKnownErrorOccuredInServerPlsContactAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Until end visit time.
        /// </summary>
        public static string UntilEndVisitTime {
            get {
                return ResourceManager.GetString("UntilEndVisitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user is admin, it cannot be deleted.
        /// </summary>
        public static string UserIsAdminCanotDelIt {
            get {
                return ResourceManager.GetString("UserIsAdminCanotDelIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user is admin, it cannot be deleted.
        /// </summary>
        public static string UserIsAdminYouCannotDeleteIt {
            get {
                return ResourceManager.GetString("UserIsAdminYouCannotDeleteIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is clinic manager already.
        /// </summary>
        public static string UserIsClinicManagerAlready {
            get {
                return ResourceManager.GetString("UserIsClinicManagerAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is managing centers, please unassign first.
        /// </summary>
        public static string UserIsManagingCentersPleaseUnassignFirst {
            get {
                return ResourceManager.GetString("UserIsManagingCentersPleaseUnassignFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not doctor, you cannot assign speciality.
        /// </summary>
        public static string UserIsNotDoctorYouCannotAssignSpeciality {
            get {
                return ResourceManager.GetString("UserIsNotDoctorYouCannotAssignSpeciality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not doctor, you cannot select expertise.
        /// </summary>
        public static string UserIsNotDoctorYouCannotSelectExpertise {
            get {
                return ResourceManager.GetString("UserIsNotDoctorYouCannotSelectExpertise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is polyclinic manager, you cannot delete it.
        /// </summary>
        public static string UserIsPolyclinicManagerCannotDelIt {
            get {
                return ResourceManager.GetString("UserIsPolyclinicManagerCannotDelIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password is invalid.
        /// </summary>
        public static string UsernameOrPasswordIsInvalid {
            get {
                return ResourceManager.GetString("UsernameOrPasswordIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User registered successfully.
        /// </summary>
        public static string UserRegisteredSuccessfully {
            get {
                return ResourceManager.GetString("UserRegisteredSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with this email alreay exists.
        /// </summary>
        public static string UserWithThisEmailExistBefore {
            get {
                return ResourceManager.GetString("UserWithThisEmailExistBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile number exists.
        /// </summary>
        public static string UserWithThisMobileExist {
            get {
                return ResourceManager.GetString("UserWithThisMobileExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid empty time period not found.
        /// </summary>
        public static string ValidEmptyTimePeriodNotFound {
            get {
                return ResourceManager.GetString("ValidEmptyTimePeriodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version pattern is not valid.
        /// </summary>
        public static string VersionPatternIsNotValid {
            get {
                return ResourceManager.GetString("VersionPatternIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We could not find the page you were looking for..
        /// </summary>
        public static string WeCouldNotFindPage {
            get {
                return ResourceManager.GetString("WeCouldNotFindPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will be canceled.
        /// </summary>
        public static string WillBeCanceled {
            get {
                return ResourceManager.GetString("WillBeCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without limitation from now.
        /// </summary>
        public static string WithoutLimitation_FromNow {
            get {
                return ResourceManager.GetString("WithoutLimitation_FromNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With starting visit time.
        /// </summary>
        public static string WithStartingVisitTime {
            get {
                return ResourceManager.GetString("WithStartingVisitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You won&apos;t be able to revert this.
        /// </summary>
        public static string WontAbleRevertThis {
            get {
                return ResourceManager.GetString("WontAbleRevertThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working schedule not found for this time. Please see working hours and request new appointment.
        /// </summary>
        public static string WorkingScheduleNotFoundForThisTime {
            get {
                return ResourceManager.GetString("WorkingScheduleNotFoundForThisTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are logged in, you cannot change role.
        /// </summary>
        public static string YouAreLoggedInAndCannotChangeRole {
            get {
                return ResourceManager.GetString("YouAreLoggedInAndCannotChangeRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are logged in, you cannot change role.
        /// </summary>
        public static string YouAreLoggedInCannotChangeRole {
            get {
                return ResourceManager.GetString("YouAreLoggedInCannotChangeRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot delete current user from clinic managers.
        /// </summary>
        public static string YouCannotDeleteCurrentUserFromClinicManagers {
            get {
                return ResourceManager.GetString("YouCannotDeleteCurrentUserFromClinicManagers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot remove admin role for this user.
        /// </summary>
        public static string YouCannotRemoveAdminRoleForThisUser {
            get {
                return ResourceManager.GetString("YouCannotRemoveAdminRoleForThisUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don’t have permission.
        /// </summary>
        public static string YouDontHavePermission {
            get {
                return ResourceManager.GetString("YouDontHavePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your appointment for doctor.
        /// </summary>
        public static string YourAppointmentForDoctor {
            get {
                return ResourceManager.GetString("YourAppointmentForDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your message was sent successfully.
        /// </summary>
        public static string YourMessageSenedToUsSuccessfully {
            get {
                return ResourceManager.GetString("YourMessageSenedToUsSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile number deleted successfully.
        /// </summary>
        public static string YourPhoneDeletedSuccessfully {
            get {
                return ResourceManager.GetString("YourPhoneDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number has been added.
        /// </summary>
        public static string YourPhoneHasBeenAdded {
            get {
                return ResourceManager.GetString("YourPhoneHasBeenAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your appointment from date.
        /// </summary>
        public static string YourTurnFromDate {
            get {
                return ResourceManager.GetString("YourTurnFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your appointment in date.
        /// </summary>
        public static string YourTurnInDate {
            get {
                return ResourceManager.GetString("YourTurnInDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your appointment is reserved successfully.
        /// </summary>
        public static string YourTurnReservedSuccessfully {
            get {
                return ResourceManager.GetString("YourTurnReservedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your appointment will be canceled.
        /// </summary>
        public static string YourTurnWillBeCanceled {
            get {
                return ResourceManager.GetString("YourTurnWillBeCanceled", resourceCulture);
            }
        }
    }
}
