//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AN.Core.Resources.EntitiesResources.Role {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RolesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RolesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AN.Core.Resources.EntitiesResources.Role.RolesResource", typeof(RolesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string admin {
            get {
                return ResourceManager.GetString("admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beauty Center Manager.
        /// </summary>
        public static string beautycentermanager {
            get {
                return ResourceManager.GetString("beautycentermanager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Center.
        /// </summary>
        public static string callcenter {
            get {
                return ResourceManager.GetString("callcenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinic manager.
        /// </summary>
        public static string clinicmanager {
            get {
                return ResourceManager.GetString("clinicmanager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor.
        /// </summary>
        public static string doctor {
            get {
                return ResourceManager.GetString("doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMS.
        /// </summary>
        public static string ems {
            get {
                return ResourceManager.GetString("ems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Care.
        /// </summary>
        public static string homecare {
            get {
                return ResourceManager.GetString("homecare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospital manager.
        /// </summary>
        public static string hospitalmanager {
            get {
                return ResourceManager.GetString("hospitalmanager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lab Manager.
        /// </summary>
        public static string labmanager {
            get {
                return ResourceManager.GetString("labmanager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Tourism.
        /// </summary>
        public static string medicaltourism {
            get {
                return ResourceManager.GetString("medicaltourism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        public static string patient {
            get {
                return ResourceManager.GetString("patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacy Manager.
        /// </summary>
        public static string pharmacymanager {
            get {
                return ResourceManager.GetString("pharmacymanager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polyclinic manager.
        /// </summary>
        public static string polyclinicmanager {
            get {
                return ResourceManager.GetString("polyclinicmanager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secretary.
        /// </summary>
        public static string secretary {
            get {
                return ResourceManager.GetString("secretary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonar Manager.
        /// </summary>
        public static string sonarmanager {
            get {
                return ResourceManager.GetString("sonarmanager", resourceCulture);
            }
        }
    }
}
