//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AN.Web.LocalResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AN.Web.LocalResource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved for.
        /// </summary>
        public static string AllRightsReservedFor {
            get {
                return ResourceManager.GetString("AllRightsReservedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android.
        /// </summary>
        public static string Android {
            get {
                return ResourceManager.GetString("Android", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        public static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AwroNore.
        /// </summary>
        public static string AwroNore {
            get {
                return ResourceManager.GetString("AwroNore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awrosoft address.
        /// </summary>
        public static string AwrosoftAddress {
            get {
                return ResourceManager.GetString("AwrosoftAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awrosoft ICT solutions company.
        /// </summary>
        public static string AwrosoftCompany {
            get {
                return ResourceManager.GetString("AwrosoftCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best doctors.
        /// </summary>
        public static string BestDoctors {
            get {
                return ResourceManager.GetString("BestDoctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Appointment System.
        /// </summary>
        public static string BookingAppointmentSystem {
            get {
                return ResourceManager.GetString("BookingAppointmentSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel This appointment and back.
        /// </summary>
        public static string CancelThisAppointAndBack {
            get {
                return ResourceManager.GetString("CancelThisAppointAndBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinic.
        /// </summary>
        public static string Clinic {
            get {
                return ResourceManager.GetString("Clinic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinic register.
        /// </summary>
        public static string ClinicRegister {
            get {
                return ResourceManager.GetString("ClinicRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinic selection.
        /// </summary>
        public static string ClinicSelection {
            get {
                return ResourceManager.GetString("ClinicSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinic shifts.
        /// </summary>
        public static string ClinicShifts {
            get {
                return ResourceManager.GetString("ClinicShifts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinic show.
        /// </summary>
        public static string ClinicShow {
            get {
                return ResourceManager.GetString("ClinicShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinic type selection.
        /// </summary>
        public static string ClinicTypeSelection {
            get {
                return ResourceManager.GetString("ClinicTypeSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common questions and answeres.
        /// </summary>
        public static string CommonQuestionsAnsweres {
            get {
                return ResourceManager.GetString("CommonQuestionsAnsweres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact numbers.
        /// </summary>
        public static string ContactNumbers {
            get {
                return ResourceManager.GetString("ContactNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string CopyRight {
            get {
                return ResourceManager.GetString("CopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date selection.
        /// </summary>
        public static string DateSelection {
            get {
                return ResourceManager.GetString("DateSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor.
        /// </summary>
        public static string Doctor {
            get {
                return ResourceManager.GetString("Doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download patient application.
        /// </summary>
        public static string DownloadPatientApp {
            get {
                return ResourceManager.GetString("DownloadPatientApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is not valid.
        /// </summary>
        public static string EmailNotValid {
            get {
                return ResourceManager.GetString("EmailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enerting data alert.
        /// </summary>
        public static string EnertingDataAlert {
            get {
                return ResourceManager.GetString("EnertingDataAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entering data.
        /// </summary>
        public static string EnteringData {
            get {
                return ResourceManager.GetString("EnteringData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evening shift.
        /// </summary>
        public static string EveningShift {
            get {
                return ResourceManager.GetString("EveningShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expertises.
        /// </summary>
        public static string Expertises {
            get {
                return ResourceManager.GetString("Expertises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final confirmation.
        /// </summary>
        public static string FinalConfirmation {
            get {
                return ResourceManager.GetString("FinalConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First available turn.
        /// </summary>
        public static string FirstAvailableTurn {
            get {
                return ResourceManager.GetString("FirstAvailableTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For reserve  appointment.
        /// </summary>
        public static string ForReserveAppointment {
            get {
                return ResourceManager.GetString("ForReserveAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From hour.
        /// </summary>
        public static string FromHour {
            get {
                return ResourceManager.GetString("FromHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full.
        /// </summary>
        public static string Full {
            get {
                return ResourceManager.GetString("Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home page.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospital.
        /// </summary>
        public static string Hospital {
            get {
                return ResourceManager.GetString("Hospital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospital register.
        /// </summary>
        public static string HospitalRegister {
            get {
                return ResourceManager.GetString("HospitalRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospitals.
        /// </summary>
        public static string Hospitals {
            get {
                return ResourceManager.GetString("Hospitals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient information.
        /// </summary>
        public static string IndividualPatientInfo {
            get {
                return ResourceManager.GetString("IndividualPatientInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruction title.
        /// </summary>
        public static string InstructionTitle {
            get {
                return ResourceManager.GetString("InstructionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance code.
        /// </summary>
        public static string InsuranceCode {
            get {
                return ResourceManager.GetString("InsuranceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance type.
        /// </summary>
        public static string InsuranceType {
            get {
                return ResourceManager.GetString("InsuranceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string IsCircadian {
            get {
                return ResourceManager.GetString("IsCircadian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is governmental.
        /// </summary>
        public static string IsGovernmental {
            get {
                return ResourceManager.GetString("IsGovernmental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Law regulations.
        /// </summary>
        public static string LawRegulations {
            get {
                return ResourceManager.GetString("LawRegulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical council number.
        /// </summary>
        public static string MedicalCouncilNumber {
            get {
                return ResourceManager.GetString("MedicalCouncilNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile notifications.
        /// </summary>
        public static string MobileAlert {
            get {
                return ResourceManager.GetString("MobileAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile applications.
        /// </summary>
        public static string MobileApps {
            get {
                return ResourceManager.GetString("MobileApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morning shift.
        /// </summary>
        public static string MorningShift {
            get {
                return ResourceManager.GetString("MorningShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News archive.
        /// </summary>
        public static string NewsArchive {
            get {
                return ResourceManager.GetString("NewsArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next step.
        /// </summary>
        public static string NextStep {
            get {
                return ResourceManager.GetString("NextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nongovernmenal clinics.
        /// </summary>
        public static string NonGovClinics {
            get {
                return ResourceManager.GetString("NonGovClinics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No item found.
        /// </summary>
        public static string NotItemFound {
            get {
                return ResourceManager.GetString("NotItemFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online payment.
        /// </summary>
        public static string OnlinePayment {
            get {
                return ResourceManager.GetString("OnlinePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online turn reservation.
        /// </summary>
        public static string OnlineTurnReservation {
            get {
                return ResourceManager.GetString("OnlineTurnReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only have appointment.
        /// </summary>
        public static string OnlyHaveTurn {
            get {
                return ResourceManager.GetString("OnlyHaveTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only show doctors which have appointment.
        /// </summary>
        public static string OnlyShowDoctorsWithHaveTurn {
            get {
                return ResourceManager.GetString("OnlyShowDoctorsWithHaveTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient info.
        /// </summary>
        public static string PatientInfo {
            get {
                return ResourceManager.GetString("PatientInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient register.
        /// </summary>
        public static string PatientRegister {
            get {
                return ResourceManager.GetString("PatientRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        public static string Person {
            get {
                return ResourceManager.GetString("Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter date.
        /// </summary>
        public static string PleaseEnterDate {
            get {
                return ResourceManager.GetString("PleaseEnterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter text only.
        /// </summary>
        public static string PleaseOnlyEnterText {
            get {
                return ResourceManager.GetString("PleaseOnlyEnterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your city.
        /// </summary>
        public static string PleaseSelectCity {
            get {
                return ResourceManager.GetString("PleaseSelectCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a date.
        /// </summary>
        public static string PleaseSelectDate {
            get {
                return ResourceManager.GetString("PleaseSelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an expertise.
        /// </summary>
        public static string PleaseSelectExpertise {
            get {
                return ResourceManager.GetString("PleaseSelectExpertise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an appointment.
        /// </summary>
        public static string PleaseSelectOneOfThisTurns {
            get {
                return ResourceManager.GetString("PleaseSelectOneOfThisTurns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select province.
        /// </summary>
        public static string PleaseSelectProvince {
            get {
                return ResourceManager.GetString("PleaseSelectProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polyclinic.
        /// </summary>
        public static string Polyclinic {
            get {
                return ResourceManager.GetString("Polyclinic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polyclinic registeration.
        /// </summary>
        public static string PolyclinicRegister {
            get {
                return ResourceManager.GetString("PolyclinicRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polyclinics.
        /// </summary>
        public static string Polyclinics {
            get {
                return ResourceManager.GetString("Polyclinics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is required.
        /// </summary>
        public static string PromptEmailRequired {
            get {
                return ResourceManager.GetString("PromptEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid email address.
        /// </summary>
        public static string PromptEnterValidEmail {
            get {
                return ResourceManager.GetString("PromptEnterValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick search by clinic name.
        /// </summary>
        public static string QuickSearchByClinicName {
            get {
                return ResourceManager.GetString("QuickSearchByClinicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick search by doctor name.
        /// </summary>
        public static string QuickSearchByDoctorName {
            get {
                return ResourceManager.GetString("QuickSearchByDoctorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regulation section link.
        /// </summary>
        public static string RegulationSectionLink {
            get {
                return ResourceManager.GetString("RegulationSectionLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remained time.
        /// </summary>
        public static string RemainedTime {
            get {
                return ResourceManager.GetString("RemainedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation.
        /// </summary>
        public static string Reservation {
            get {
                return ResourceManager.GetString("Reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve appointment.
        /// </summary>
        public static string ReserveAppointment {
            get {
                return ResourceManager.GetString("ReserveAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve appointment for clinics and health centers.
        /// </summary>
        public static string ReserveAppointmentForClinicsAndHealthCenters {
            get {
                return ResourceManager.GetString("ReserveAppointmentForClinicsAndHealthCenters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve appointment for doctor.
        /// </summary>
        public static string ReserveAppointmentForDoctor {
            get {
                return ResourceManager.GetString("ReserveAppointmentForDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve this appointment.
        /// </summary>
        public static string ReserveThisTurn {
            get {
                return ResourceManager.GetString("ReserveThisTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve appointment.
        /// </summary>
        public static string ReserveTurn {
            get {
                return ResourceManager.GetString("ReserveTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety security.
        /// </summary>
        public static string SafetySecurity {
            get {
                return ResourceManager.GetString("SafetySecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety security notification.
        /// </summary>
        public static string SafetySecurityAlert {
            get {
                return ResourceManager.GetString("SafetySecurityAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search doctors.
        /// </summary>
        public static string SearchDoctors {
            get {
                return ResourceManager.GetString("SearchDoctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second name.
        /// </summary>
        public static string SecondName {
            get {
                return ResourceManager.GetString("SecondName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select city.
        /// </summary>
        public static string SelectCity {
            get {
                return ResourceManager.GetString("SelectCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected expertises.
        /// </summary>
        public static string SelectedExpertises {
            get {
                return ResourceManager.GetString("SelectedExpertises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select province.
        /// </summary>
        public static string SelectProvince {
            get {
                return ResourceManager.GetString("SelectProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        public static string Sum {
            get {
                return ResourceManager.GetString("Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string TimeTable {
            get {
                return ResourceManager.GetString("TimeTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TimeTableDesc {
            get {
                return ResourceManager.GetString("TimeTableDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To hour.
        /// </summary>
        public static string ToHour {
            get {
                return ResourceManager.GetString("ToHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training.
        /// </summary>
        public static string Training {
            get {
                return ResourceManager.GetString("Training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment .
        /// </summary>
        public static string Turn {
            get {
                return ResourceManager.GetString("Turn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment cancellation.
        /// </summary>
        public static string TurnCancellation {
            get {
                return ResourceManager.GetString("TurnCancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment proceeding notification.
        /// </summary>
        public static string TurnProceedingAlert {
            get {
                return ResourceManager.GetString("TurnProceedingAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment proceeding cancellation.
        /// </summary>
        public static string TurnProceedingCancellation {
            get {
                return ResourceManager.GetString("TurnProceedingCancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointments.
        /// </summary>
        public static string Turns {
            get {
                return ResourceManager.GetString("Turns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appoitment selection.
        /// </summary>
        public static string TurnSelection {
            get {
                return ResourceManager.GetString("TurnSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Useful article.
        /// </summary>
        public static string UsefulArticle {
            get {
                return ResourceManager.GetString("UsefulArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Useful links.
        /// </summary>
        public static string UsefulLinks {
            get {
                return ResourceManager.GetString("UsefulLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View and reserve appointment.
        /// </summary>
        public static string ViewAndReserveAppointment {
            get {
                return ResourceManager.GetString("ViewAndReserveAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View and track appointments.
        /// </summary>
        public static string ViewAndTrackingAppoints {
            get {
                return ResourceManager.GetString("ViewAndTrackingAppoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View scheduling.
        /// </summary>
        public static string ViewScheduling {
            get {
                return ResourceManager.GetString("ViewScheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit date selection.
        /// </summary>
        public static string VisitDateSelection {
            get {
                return ResourceManager.GetString("VisitDateSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit time.
        /// </summary>
        public static string VisitTime {
            get {
                return ResourceManager.GetString("VisitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit time notification.
        /// </summary>
        public static string VisitTimeAlert {
            get {
                return ResourceManager.GetString("VisitTimeAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your appointment.
        /// </summary>
        public static string YourAppointment {
            get {
                return ResourceManager.GetString("YourAppointment", resourceCulture);
            }
        }
    }
}
