//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AN.Core.Domain
{
    using AN.Core.Data;
    using AN.Core.Enums;
    using AN.Core.Models;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using NetTopologySuite.Geometries;
    public partial class Clinic : BaseEntity
    {
        public Clinic()
        {            
            this.ShiftCenters = new HashSet<ShiftCenter>();            
            this.ClinicUsers = new HashSet<ClinicPersons>();
        }        
      
        public string Name { get; set; }
        public string Name_Ku { get; set; }      
        public string Name_Ar { get; set; }

        public bool IsIndependent { get; set; }
      
        public bool IsGovernmental { get; set; } = false;
       
        public bool IsHostelry { get; set; } = false;
       
        public ClinicType Type { get; set; }

        public int? CityId { get; set; }
       
        public string Address { get; set; }
        public string Address_Ku { get; set; }      
        public string Address_Ar { get; set; }
       
        public string Description { get; set; }        
        public string Description_Ku { get; set; }        
        public string Description_Ar { get; set; }

        /// <summary>
        /// پیام اطلاع رسانی بعد از رزرو نوبت روی اپ و سایت
        /// </summary>       
        public string FinalBookMessage { get; set; }       
        public string FinalBookMessage_Ku { get; set; }       
        public string FinalBookMessage_Ar { get; set; }

        /// <summary>
        /// متن پیامک اطلاع رسانی بعد از رزرو نوبت
        /// </summary>        
        public string FinalBookSMSMessage { get; set; }       
        public string FinalBookSMSMessage_Ku { get; set; }       
        public string FinalBookSMSMessage_Ar { get; set; }

        public int? HospitalId { get; set; }

        public Point Location { get; set; }

        public bool IsApproved { get; set; } = false;
       
        public string Notification{ get; set; }       
        public string Notification_Ku { get; set; }       
        public string Notification_Ar { get; set; }

        public string _PhoneNumbers { get; set; }
        [NotMapped]
        public List<ShiftCenterPhoneModel> PhoneNumbers
        {
            get { return _PhoneNumbers == null ? null : JsonConvert.DeserializeObject<List<ShiftCenterPhoneModel>>(_PhoneNumbers); }
            set { _PhoneNumbers = JsonConvert.SerializeObject(value); }
        }

        public string _Images { get; set; }
        [NotMapped]
        public List<HealthCenterImageEntityModel> Images
        {
            get { return _Images == null ? null : JsonConvert.DeserializeObject<List<HealthCenterImageEntityModel>>(_Images); }
            set { _Images = JsonConvert.SerializeObject(value); }
        }

        public string _Vocations { get; set; }
        [NotMapped]
        public List<VocationModel> Vocations
        {
            get { return _Vocations == null ? null : JsonConvert.DeserializeObject<List<VocationModel>>(_Vocations); }
            set { _Vocations = JsonConvert.SerializeObject(value); }
        }

        public string Logo { get; set; }

        [NotMapped]
        public string RealLogo => !string.IsNullOrEmpty(Logo) ? Logo : "/images/logo.png";

        public virtual Hospital Hospital { get; set; }
       
        public virtual City City { get; set; }
                
        public virtual ICollection<ShiftCenter> ShiftCenters { get; set; }       

        public virtual ICollection<ClinicPersons> ClinicUsers { get; set; }       

    }
}
