//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AN.Core.Domain
{
    using AN.Core.Data;
    using System;
    using System.ComponentModel.DataAnnotations.Schema;

    [Serializable]
    public class PaymentInfo : BaseEntity
    {
        [NotMapped]
        public override int Id { get => base.Id; set => base.Id = value; }

        public int AppointmentId { get; set; }
        public long OrderId { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
        public long SaleReferenceId { get; set; }
        public long SaleOrderId { get; set; }
       
        public virtual Appointment Appointment { get; set; }
    }
}
