//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AN.Core.Domain
{
    using AN.Core.Data;
    using AN.Core.Enums;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class Schedule : BaseEntity
    {
        public Schedule()
        {
            Insurances = new HashSet<ScheduleInsurance>();
        }

        public DateTime Start_DateTime { get; set; }
      
        public DateTime End_DateTime { get; set; }
      
        public string DayOfWeek { get; set; }
       
        public bool IsAvailable { get; set; }

        /// <summary>
        /// تعداد کل نوبت های قابل رزرو در این ساعت کاری
        /// </summary>
        public int MaxCount { get; set; }
       
        public string Description { get; set; }
        public string Description_Ku { get; set; }       
        public string Description_Ar { get; set; }       
      
        public int ServiceSupplyId { get; set; }

        public int ShiftCenterServiceId { get; set; }

        public PrerequisiteType Prerequisite { get; set; } = PrerequisiteType.WithoutPrerequisite;

        public ScheduleShift Shift { get; set; } = ScheduleShift.Morning;
        
        public virtual ServiceSupply ServiceSupply { get; set; }
       
        public virtual ShiftCenterService ShiftCenterService { get; set; }

        public virtual ICollection<ScheduleInsurance> Insurances { get; set; }
    }
}
