//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AN.Core.Resources.Enums {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnumResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AN.Core.Resources.Enums.EnumResource", typeof(EnumResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A-.
        /// </summary>
        public static string a_negative {
            get {
                return ResourceManager.GetString("a_negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A+.
        /// </summary>
        public static string a_positive {
            get {
                return ResourceManager.GetString("a_positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AB-.
        /// </summary>
        public static string ab_negative {
            get {
                return ResourceManager.GetString("ab_negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AB+.
        /// </summary>
        public static string ab_positive {
            get {
                return ResourceManager.GetString("ab_positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment.
        /// </summary>
        public static string appointment {
            get {
                return ResourceManager.GetString("appointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string approved {
            get {
                return ResourceManager.GetString("approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asc.
        /// </summary>
        public static string ascending {
            get {
                return ResourceManager.GetString("ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B-.
        /// </summary>
        public static string b_negative {
            get {
                return ResourceManager.GetString("b_negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B+.
        /// </summary>
        public static string b_positive {
            get {
                return ResourceManager.GetString("b_positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beauty Centers.
        /// </summary>
        public static string beautyCenter {
            get {
                return ResourceManager.GetString("beautyCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barber.
        /// </summary>
        public static string berber {
            get {
                return ResourceManager.GetString("berber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Count.
        /// </summary>
        public static string booking {
            get {
                return ResourceManager.GetString("booking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break Time.
        /// </summary>
        public static string breaktime {
            get {
                return ResourceManager.GetString("breaktime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-up.
        /// </summary>
        public static string checkup {
            get {
                return ResourceManager.GetString("checkup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string completed {
            get {
                return ResourceManager.GetString("completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string created {
            get {
                return ResourceManager.GetString("created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CT-Scan.
        /// </summary>
        public static string CTScan {
            get {
                return ResourceManager.GetString("CTScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dentists.
        /// </summary>
        public static string dentist {
            get {
                return ResourceManager.GetString("dentist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desc.
        /// </summary>
        public static string descending {
            get {
                return ResourceManager.GetString("descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string done {
            get {
                return ResourceManager.GetString("done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        public static string empty {
            get {
                return ResourceManager.GetString("empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Offer.
        /// </summary>
        public static string emptyoffer {
            get {
                return ResourceManager.GetString("emptyoffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string female {
            get {
                return ResourceManager.GetString("female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healthy Lifestyle.
        /// </summary>
        public static string healthyLifeStyle {
            get {
                return ResourceManager.GetString("healthyLifeStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Care.
        /// </summary>
        public static string homecare {
            get {
                return ResourceManager.GetString("homecare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InProgress Appointment.
        /// </summary>
        public static string inprogressappointment {
            get {
                return ResourceManager.GetString("inprogressappointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laboratory.
        /// </summary>
        public static string laboratory {
            get {
                return ResourceManager.GetString("laboratory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string male {
            get {
                return ResourceManager.GetString("male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MRI.
        /// </summary>
        public static string MRI {
            get {
                return ResourceManager.GetString("MRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nail spa.
        /// </summary>
        public static string nailSpa {
            get {
                return ResourceManager.GetString("nailSpa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O-.
        /// </summary>
        public static string o_negative {
            get {
                return ResourceManager.GetString("o_negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O+.
        /// </summary>
        public static string o_positive {
            get {
                return ResourceManager.GetString("o_positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Appointment.
        /// </summary>
        public static string offerappointment {
            get {
                return ResourceManager.GetString("offerappointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On the way.
        /// </summary>
        public static string on_the_way {
            get {
                return ResourceManager.GetString("on_the_way", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optometrist.
        /// </summary>
        public static string optometrist {
            get {
                return ResourceManager.GetString("optometrist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string pending {
            get {
                return ResourceManager.GetString("pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacy.
        /// </summary>
        public static string pharmacy {
            get {
                return ResourceManager.GetString("pharmacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctors.
        /// </summary>
        public static string polyclinic {
            get {
                return ResourceManager.GetString("polyclinic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string processing {
            get {
                return ResourceManager.GetString("processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radiology.
        /// </summary>
        public static string radiology {
            get {
                return ResourceManager.GetString("radiology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string rejected {
            get {
                return ResourceManager.GetString("rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salon.
        /// </summary>
        public static string salon {
            get {
                return ResourceManager.GetString("salon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonography.
        /// </summary>
        public static string sonography {
            get {
                return ResourceManager.GetString("sonography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string unknown {
            get {
                return ResourceManager.GetString("unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visits Count.
        /// </summary>
        public static string visits {
            get {
                return ResourceManager.GetString("visits", resourceCulture);
            }
        }
    }
}
