//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AN.Core.Resources.UI.AdminPanel {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PanelResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PanelResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AN.Core.Resources.UI.AdminPanel.PanelResource", typeof(PanelResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active days ahead.
        /// </summary>
        public static string ActiveDaysAhead {
            get {
                return ResourceManager.GetString("ActiveDaysAhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active doctor.
        /// </summary>
        public static string ActiveDoctor {
            get {
                return ResourceManager.GetString("ActiveDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add and delete managers.
        /// </summary>
        public static string AddAndDeleteManagers {
            get {
                return ResourceManager.GetString("AddAndDeleteManagers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new.
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new clinic.
        /// </summary>
        public static string AddNewClinic {
            get {
                return ResourceManager.GetString("AddNewClinic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new doctor.
        /// </summary>
        public static string AddNewDoctor {
            get {
                return ResourceManager.GetString("AddNewDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new expertise.
        /// </summary>
        public static string AddNewExpertise {
            get {
                return ResourceManager.GetString("AddNewExpertise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new file.
        /// </summary>
        public static string AddNewFile {
            get {
                return ResourceManager.GetString("AddNewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Group.
        /// </summary>
        public static string AddNewGroup {
            get {
                return ResourceManager.GetString("AddNewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new hospital.
        /// </summary>
        public static string AddNewHospital {
            get {
                return ResourceManager.GetString("AddNewHospital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new insurance.
        /// </summary>
        public static string AddNewInsurance {
            get {
                return ResourceManager.GetString("AddNewInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new patient.
        /// </summary>
        public static string AddNewPatient {
            get {
                return ResourceManager.GetString("AddNewPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Person.
        /// </summary>
        public static string AddNewPerson {
            get {
                return ResourceManager.GetString("AddNewPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new place.
        /// </summary>
        public static string AddNewPlace {
            get {
                return ResourceManager.GetString("AddNewPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new polyclinic.
        /// </summary>
        public static string AddNewPolyclinic {
            get {
                return ResourceManager.GetString("AddNewPolyclinic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new schedule.
        /// </summary>
        public static string AddNewSchedule {
            get {
                return ResourceManager.GetString("AddNewSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Service.
        /// </summary>
        public static string AddNewService {
            get {
                return ResourceManager.GetString("AddNewService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new user.
        /// </summary>
        public static string AddNewUser {
            get {
                return ResourceManager.GetString("AddNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add schedule.
        /// </summary>
        public static string AddSchedule {
            get {
                return ResourceManager.GetString("AddSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin panel.
        /// </summary>
        public static string AdminPanel {
            get {
                return ResourceManager.GetString("AdminPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All list.
        /// </summary>
        public static string AllList {
            get {
                return ResourceManager.GetString("AllList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All messages.
        /// </summary>
        public static string AllMessages {
            get {
                return ResourceManager.GetString("AllMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All roles.
        /// </summary>
        public static string AllRoles {
            get {
                return ResourceManager.GetString("AllRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All system appointmetns.
        /// </summary>
        public static string AllSystemTurns {
            get {
                return ResourceManager.GetString("AllSystemTurns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All appoitments.
        /// </summary>
        public static string AllTurns {
            get {
                return ResourceManager.GetString("AllTurns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Announcement.
        /// </summary>
        public static string Announcement {
            get {
                return ResourceManager.GetString("Announcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Announcements list.
        /// </summary>
        public static string AnnouncementsList {
            get {
                return ResourceManager.GetString("AnnouncementsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Announcement SMSs.
        /// </summary>
        public static string AnnouncementSMSs {
            get {
                return ResourceManager.GetString("AnnouncementSMSs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointments count.
        /// </summary>
        public static string AppointmentsCount {
            get {
                return ResourceManager.GetString("AppointmentsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve request.
        /// </summary>
        public static string ApproveRequest {
            get {
                return ResourceManager.GetString("ApproveRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign new doctor.
        /// </summary>
        public static string AssignNewDoctor {
            get {
                return ResourceManager.GetString("AssignNewDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign new manager.
        /// </summary>
        public static string AssignNewManager {
            get {
                return ResourceManager.GetString("AssignNewManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign to clinic.
        /// </summary>
        public static string AssignToClinic {
            get {
                return ResourceManager.GetString("AssignToClinic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign to hospital.
        /// </summary>
        public static string AssignToHospital {
            get {
                return ResourceManager.GetString("AssignToHospital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign to polyclinic.
        /// </summary>
        public static string AssignToPolyclinic {
            get {
                return ResourceManager.GetString("AssignToPolyclinic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AwroNore&apos;s manager.
        /// </summary>
        public static string AwroNoreManager {
            get {
                return ResourceManager.GetString("AwroNoreManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before start visit.
        /// </summary>
        public static string BeforeStartVisit {
            get {
                return ResourceManager.GetString("BeforeStartVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blacklist.
        /// </summary>
        public static string BlackList {
            get {
                return ResourceManager.GetString("BlackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked IPs.
        /// </summary>
        public static string BlockedIPs {
            get {
                return ResourceManager.GetString("BlockedIPs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel all.
        /// </summary>
        public static string CancelAll {
            get {
                return ResourceManager.GetString("CancelAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel and notify.
        /// </summary>
        public static string CancelAndNotify {
            get {
                return ResourceManager.GetString("CancelAndNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel and prevent reserve again.
        /// </summary>
        public static string CancelAndPreventReserveAgain {
            get {
                return ResourceManager.GetString("CancelAndPreventReserveAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel and return back to empty list.
        /// </summary>
        public static string CancelAndReturnBackToEmptyList {
            get {
                return ResourceManager.GetString("CancelAndReturnBackToEmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled appointments.
        /// </summary>
        public static string CanceledTurns {
            get {
                return ResourceManager.GetString("CanceledTurns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel all, and disable doctor.
        /// </summary>
        public static string CancellAllAndDisableDoctor {
            get {
                return ResourceManager.GetString("CancellAllAndDisableDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel appointment and don’t resrve again.
        /// </summary>
        public static string CancelTurnAndDontResrveAgain {
            get {
                return ResourceManager.GetString("CancelTurnAndDontResrveAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel appointment and return to empty list.
        /// </summary>
        public static string CancelTurnAndReturnToEmptyList {
            get {
                return ResourceManager.GetString("CancelTurnAndReturnToEmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change clinic.
        /// </summary>
        public static string ChangeClinic {
            get {
                return ResourceManager.GetString("ChangeClinic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change hospital.
        /// </summary>
        public static string ChangeHospital {
            get {
                return ResourceManager.GetString("ChangeHospital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change polyclinic.
        /// </summary>
        public static string ChangePolyclinic {
            get {
                return ResourceManager.GetString("ChangePolyclinic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinic doctors.
        /// </summary>
        public static string ClinicDoctors {
            get {
                return ResourceManager.GetString("ClinicDoctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinic name.
        /// </summary>
        public static string ClinicName {
            get {
                return ResourceManager.GetString("ClinicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinic polyclinics list.
        /// </summary>
        public static string ClinicPolyclinicsList {
            get {
                return ResourceManager.GetString("ClinicPolyclinicsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinic status.
        /// </summary>
        public static string ClinicStatus {
            get {
                return ResourceManager.GetString("ClinicStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinic appointments.
        /// </summary>
        public static string ClinicTurns {
            get {
                return ResourceManager.GetString("ClinicTurns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinic appointments report.
        /// </summary>
        public static string ClinicTurnsReport {
            get {
                return ResourceManager.GetString("ClinicTurnsReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinic type.
        /// </summary>
        public static string ClinicType {
            get {
                return ResourceManager.GetString("ClinicType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinic vocations.
        /// </summary>
        public static string ClinicVocations {
            get {
                return ResourceManager.GetString("ClinicVocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Doctors.
        /// </summary>
        public static string CurrentDoctors {
            get {
                return ResourceManager.GetString("CurrentDoctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current doctors list.
        /// </summary>
        public static string CurrentDoctorsList {
            get {
                return ResourceManager.GetString("CurrentDoctorsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current managers list.
        /// </summary>
        public static string CurrentManagersList {
            get {
                return ResourceManager.GetString("CurrentManagersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted appointments.
        /// </summary>
        public static string DeletedTurns {
            get {
                return ResourceManager.GetString("DeletedTurns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable doctor.
        /// </summary>
        public static string DisableDcotor {
            get {
                return ResourceManager.GetString("DisableDcotor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable doctor for all day.
        /// </summary>
        public static string DisableDoctorForAllDay {
            get {
                return ResourceManager.GetString("DisableDoctorForAllDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor expertises list.
        /// </summary>
        public static string DoctorExpertisesList {
            get {
                return ResourceManager.GetString("DoctorExpertisesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The doctor has pending appointments.
        /// </summary>
        public static string DoctorHavePendingTurns {
            get {
                return ResourceManager.GetString("DoctorHavePendingTurns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor name.
        /// </summary>
        public static string DoctorName {
            get {
                return ResourceManager.GetString("DoctorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctors active times.
        /// </summary>
        public static string DoctorsActiveTimes {
            get {
                return ResourceManager.GetString("DoctorsActiveTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctors expertises.
        /// </summary>
        public static string DoctorsExpertises {
            get {
                return ResourceManager.GetString("DoctorsExpertises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctors of.
        /// </summary>
        public static string DoctorsOf {
            get {
                return ResourceManager.GetString("DoctorsOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctors report.
        /// </summary>
        public static string DoctorsReport {
            get {
                return ResourceManager.GetString("DoctorsReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done appointments.
        /// </summary>
        public static string DoneTurns {
            get {
                return ResourceManager.GetString("DoneTurns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to approve this item?.
        /// </summary>
        public static string DoYouWantToApproveThisItem {
            get {
                return ResourceManager.GetString("DoYouWantToApproveThisItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to archive this message?.
        /// </summary>
        public static string DoYouWantToArchiveThisMessage {
            get {
                return ResourceManager.GetString("DoYouWantToArchiveThisMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this item?.
        /// </summary>
        public static string DoYouWantToDeleteThisItem {
            get {
                return ResourceManager.GetString("DoYouWantToDeleteThisItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DoYouWantToDoThisTurn {
            get {
                return ResourceManager.GetString("DoYouWantToDoThisTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit clinic.
        /// </summary>
        public static string EditClinic {
            get {
                return ResourceManager.GetString("EditClinic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit doctor information.
        /// </summary>
        public static string EditDoctorInfo {
            get {
                return ResourceManager.GetString("EditDoctorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit expertise.
        /// </summary>
        public static string EditExpertise {
            get {
                return ResourceManager.GetString("EditExpertise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit expertise category.
        /// </summary>
        public static string EditExpertiseCategory {
            get {
                return ResourceManager.GetString("EditExpertiseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit hospital.
        /// </summary>
        public static string EditHospital {
            get {
                return ResourceManager.GetString("EditHospital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit insurance.
        /// </summary>
        public static string EditInsurance {
            get {
                return ResourceManager.GetString("EditInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit place.
        /// </summary>
        public static string EditPlace {
            get {
                return ResourceManager.GetString("EditPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit schedule.
        /// </summary>
        public static string EditSchedule {
            get {
                return ResourceManager.GetString("EditSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user information.
        /// </summary>
        public static string EditUserInfo {
            get {
                return ResourceManager.GetString("EditUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit vacation day.
        /// </summary>
        public static string EditVocationDay {
            get {
                return ResourceManager.GetString("EditVocationDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable doctor.
        /// </summary>
        public static string EnableDoctor {
            get {
                return ResourceManager.GetString("EnableDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Two Factor Authentication.
        /// </summary>
        public static string EnableTwoFactorAuthentication {
            get {
                return ResourceManager.GetString("EnableTwoFactorAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End reservation.
        /// </summary>
        public static string EndReservation {
            get {
                return ResourceManager.GetString("EndReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number must be bigger than 0.
        /// </summary>
        public static string Err_NumberMustBeBiggerThanZero {
            get {
                return ResourceManager.GetString("Err_NumberMustBeBiggerThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be 6 digits in length.
        /// </summary>
        public static string Err_PasswordMustBe6Digit {
            get {
                return ResourceManager.GetString("Err_PasswordMustBe6Digit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        public static string Err_PasswordsAreNotMatch {
            get {
                return ResourceManager.GetString("Err_PasswordsAreNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range between 1 and 100.
        /// </summary>
        public static string Err_RangeBetween1And100 {
            get {
                return ResourceManager.GetString("Err_RangeBetween1And100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range between 3 and 100.
        /// </summary>
        public static string Err_RangeBetween3And100 {
            get {
                return ResourceManager.GetString("Err_RangeBetween3And100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expertise categories.
        /// </summary>
        public static string ExpertiseCategories {
            get {
                return ResourceManager.GetString("ExpertiseCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expertise categories list.
        /// </summary>
        public static string ExpertiseCategoriesList {
            get {
                return ResourceManager.GetString("ExpertiseCategoriesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expertise category.
        /// </summary>
        public static string ExpertiseCategory {
            get {
                return ResourceManager.GetString("ExpertiseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expertises.
        /// </summary>
        public static string Expertises {
            get {
                return ResourceManager.GetString("Expertises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final book.
        /// </summary>
        public static string FinalBook {
            get {
                return ResourceManager.GetString("FinalBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First available from time to time.
        /// </summary>
        public static string FirstAvailableFromTimeToTime {
            get {
                return ResourceManager.GetString("FirstAvailableFromTimeToTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First avilable turn in date.
        /// </summary>
        public static string FirstAvilableTurnInDate {
            get {
                return ResourceManager.GetString("FirstAvilableTurnInDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General schedule.
        /// </summary>
        public static string GeneralSchedule {
            get {
                return ResourceManager.GetString("GeneralSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has new messages.
        /// </summary>
        public static string HasNewMessages {
            get {
                return ResourceManager.GetString("HasNewMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospital name.
        /// </summary>
        public static string HospitalName {
            get {
                return ResourceManager.GetString("HospitalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In past week.
        /// </summary>
        public static string InPastWeek {
            get {
                return ResourceManager.GetString("InPastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In progress appointmets.
        /// </summary>
        public static string InprogressTurns {
            get {
                return ResourceManager.GetString("InprogressTurns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurances.
        /// </summary>
        public static string Insurances {
            get {
                return ResourceManager.GetString("Insurances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is governant.
        /// </summary>
        public static string IsGovernant {
            get {
                return ResourceManager.GetString("IsGovernant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is hosterly.
        /// </summary>
        public static string IsHosterly {
            get {
                return ResourceManager.GetString("IsHosterly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item is used, you cannot delete it.
        /// </summary>
        public static string ItemIsUsedYouCannotDeleteIt {
            get {
                return ResourceManager.GetString("ItemIsUsedYouCannotDeleteIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last week appointments.
        /// </summary>
        public static string LastWeekAppointments {
            get {
                return ResourceManager.GetString("LastWeekAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage expertises categories.
        /// </summary>
        public static string ManageExpertisesCategories {
            get {
                return ResourceManager.GetString("ManageExpertisesCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage polyclinic services.
        /// </summary>
        public static string ManagePolyclinicServices {
            get {
                return ResourceManager.GetString("ManagePolyclinicServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical council number.
        /// </summary>
        public static string MedicalCouncilNumber {
            get {
                return ResourceManager.GetString("MedicalCouncilNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move appoitnment.
        /// </summary>
        public static string MoveTurn {
            get {
                return ResourceManager.GetString("MoveTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor is not defined.
        /// </summary>
        public static string Msg_DoctorNotDefined {
            get {
                return ResourceManager.GetString("Msg_DoctorNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager is not defined.
        /// </summary>
        public static string Msg_ManagerNotDefined {
            get {
                return ResourceManager.GetString("Msg_ManagerNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No expertise is defined.
        /// </summary>
        public static string Msg_NoExpertiseDefined {
            get {
                return ResourceManager.GetString("Msg_NoExpertiseDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select date.
        /// </summary>
        public static string Msg_PleaseSelectDate {
            get {
                return ResourceManager.GetString("Msg_PleaseSelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New expertise.
        /// </summary>
        public static string NewExpertise {
            get {
                return ResourceManager.GetString("NewExpertise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New appointment.
        /// </summary>
        public static string NewTurns {
            get {
                return ResourceManager.GetString("NewTurns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to show.
        /// </summary>
        public static string NoDataToShow {
            get {
                return ResourceManager.GetString("NoDataToShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hospital independent clinic.
        /// </summary>
        public static string NoHospital_IndependentClinic {
            get {
                return ResourceManager.GetString("NoHospital_IndependentClinic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online reservation percentage.
        /// </summary>
        public static string OnlineReservationPercentage {
            get {
                return ResourceManager.GetString("OnlineReservationPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only disable doctor.
        /// </summary>
        public static string OnlyDisableDoctor {
            get {
                return ResourceManager.GetString("OnlyDisableDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of schedule.
        /// </summary>
        public static string OutOfSchedule {
            get {
                return ResourceManager.GetString("OutOfSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Info.
        /// </summary>
        public static string PatientInfo {
            get {
                return ResourceManager.GetString("PatientInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Name.
        /// </summary>
        public static string PatientName {
            get {
                return ResourceManager.GetString("PatientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending appointments.
        /// </summary>
        public static string PendingTurns {
            get {
                return ResourceManager.GetString("PendingTurns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal information.
        /// </summary>
        public static string PersonalInfo {
            get {
                return ResourceManager.GetString("PersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select role.
        /// </summary>
        public static string PleaseSelectRole {
            get {
                return ResourceManager.GetString("PleaseSelectRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polyclinic doctors.
        /// </summary>
        public static string PolyclinicDoctors {
            get {
                return ResourceManager.GetString("PolyclinicDoctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polyclinic doctors list.
        /// </summary>
        public static string PolyclinicDoctorsList {
            get {
                return ResourceManager.GetString("PolyclinicDoctorsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General schedule.
        /// </summary>
        public static string PolyclinicGeneralSchedule {
            get {
                return ResourceManager.GetString("PolyclinicGeneralSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polyclinic managers.
        /// </summary>
        public static string PolyclinicManagers {
            get {
                return ResourceManager.GetString("PolyclinicManagers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polyclinic name.
        /// </summary>
        public static string PolyclinicName {
            get {
                return ResourceManager.GetString("PolyclinicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polyclinic phone number.
        /// </summary>
        public static string PolyclinicPhone {
            get {
                return ResourceManager.GetString("PolyclinicPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polyclinic prefix.
        /// </summary>
        public static string PolyclinicPrefix {
            get {
                return ResourceManager.GetString("PolyclinicPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of polyclinics.
        /// </summary>
        public static string PolyclinicsCount {
            get {
                return ResourceManager.GetString("PolyclinicsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of polyclinics.
        /// </summary>
        public static string PolyclinicsList {
            get {
                return ResourceManager.GetString("PolyclinicsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polyclinics with new appointments.
        /// </summary>
        public static string PolyclinicsWithNewTurns {
            get {
                return ResourceManager.GetString("PolyclinicsWithNewTurns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polyclinic appointments.
        /// </summary>
        public static string PolyclinicTurns {
            get {
                return ResourceManager.GetString("PolyclinicTurns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepayment percentage.
        /// </summary>
        public static string PrepaymentPercentage {
            get {
                return ResourceManager.GetString("PrepaymentPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register polyclinic requests.
        /// </summary>
        public static string RegisterPolyclinicRequests {
            get {
                return ResourceManager.GetString("RegisterPolyclinicRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register requests.
        /// </summary>
        public static string RegisterRequests {
            get {
                return ResourceManager.GetString("RegisterRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting.
        /// </summary>
        public static string Reporting {
            get {
                return ResourceManager.GetString("Reporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Sonar.
        /// </summary>
        public static string RequestSonar {
            get {
                return ResourceManager.GetString("RequestSonar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation announcement message.
        /// </summary>
        public static string ReservationAnnouncementMessage {
            get {
                return ResourceManager.GetString("ReservationAnnouncementMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation announcement SMS.
        /// </summary>
        public static string ReservationAnnouncementSMS {
            get {
                return ResourceManager.GetString("ReservationAnnouncementSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation limitation before visit.
        /// </summary>
        public static string ReservationLimitationBeforeVisit {
            get {
                return ResourceManager.GetString("ReservationLimitationBeforeVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation limitation for days.
        /// </summary>
        public static string ReservationLimitationForDays {
            get {
                return ResourceManager.GetString("ReservationLimitationForDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve appointment.
        /// </summary>
        public static string ReserveTurn {
            get {
                return ResourceManager.GetString("ReserveTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve appointmet outside.
        /// </summary>
        public static string ReserveTurnOutSide {
            get {
                return ResourceManager.GetString("ReserveTurnOutSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve appointment channe is statistics.
        /// </summary>
        public static string ReserveTurnsChannelsStatistics {
            get {
                return ResourceManager.GetString("ReserveTurnsChannelsStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string Resources {
            get {
                return ResourceManager.GetString("Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduling.
        /// </summary>
        public static string Scheduling {
            get {
                return ResourceManager.GetString("Scheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scientific grade.
        /// </summary>
        public static string ScientificGrade {
            get {
                return ResourceManager.GetString("ScientificGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Center Type.
        /// </summary>
        public static string SelectCenterType {
            get {
                return ResourceManager.GetString("SelectCenterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select clinic manager.
        /// </summary>
        public static string SelectClinicManager {
            get {
                return ResourceManager.GetString("SelectClinicManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select polyclinic manager.
        /// </summary>
        public static string SelectPolyClinicManager {
            get {
                return ResourceManager.GetString("SelectPolyClinicManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to another doctor.
        /// </summary>
        public static string SendToAnotherDoctor {
            get {
                return ResourceManager.GetString("SendToAnotherDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set doctor availability.
        /// </summary>
        public static string SetDoctorAvailability {
            get {
                return ResourceManager.GetString("SetDoctorAvailability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set manual schedule.
        /// </summary>
        public static string SetManualSchedule {
            get {
                return ResourceManager.GetString("SetManualSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set special schedule for doctor.
        /// </summary>
        public static string SetSpecialScheduleForDoctor {
            get {
                return ResourceManager.GetString("SetSpecialScheduleForDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all messages.
        /// </summary>
        public static string ShowAllMessages {
            get {
                return ResourceManager.GetString("ShowAllMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show this date appointments.
        /// </summary>
        public static string ShowThisDateTurns {
            get {
                return ResourceManager.GetString("ShowThisDateTurns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simultaneous with start visit.
        /// </summary>
        public static string SimultaneousWithStartVisit {
            get {
                return ResourceManager.GetString("SimultaneousWithStartVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonar Requests.
        /// </summary>
        public static string SonarRequests {
            get {
                return ResourceManager.GetString("SonarRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start reservation.
        /// </summary>
        public static string StartReservation {
            get {
                return ResourceManager.GetString("StartReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start reservation date.
        /// </summary>
        public static string StartReservationDate {
            get {
                return ResourceManager.GetString("StartReservationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start visit.
        /// </summary>
        public static string StartVisit {
            get {
                return ResourceManager.GetString("StartVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To current clinic doctors.
        /// </summary>
        public static string ToCurrentClinicDoctors {
            get {
                return ResourceManager.GetString("ToCurrentClinicDoctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today appointments.
        /// </summary>
        public static string TodayTurns {
            get {
                return ResourceManager.GetString("TodayTurns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To first available appointment.
        /// </summary>
        public static string ToFirstAvailableTurn {
            get {
                return ResourceManager.GetString("ToFirstAvailableTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To other clinic doctors.
        /// </summary>
        public static string ToOtherClinicDoctors {
            get {
                return ResourceManager.GetString("ToOtherClinicDoctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total visits.
        /// </summary>
        public static string TotalVisits {
            get {
                return ResourceManager.GetString("TotalVisits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totally.
        /// </summary>
        public static string Totaly {
            get {
                return ResourceManager.GetString("Totaly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment count.
        /// </summary>
        public static string TurnsCount {
            get {
                return ResourceManager.GetString("TurnsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment List.
        /// </summary>
        public static string TurnsList {
            get {
                return ResourceManager.GetString("TurnsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment report.
        /// </summary>
        public static string TurnsReport {
            get {
                return ResourceManager.GetString("TurnsReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointments special report.
        /// </summary>
        public static string TurnsSpecialReport {
            get {
                return ResourceManager.GetString("TurnsSpecialReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointments statistics.
        /// </summary>
        public static string TurnsStatistics {
            get {
                return ResourceManager.GetString("TurnsStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload new version.
        /// </summary>
        public static string UploadNewVersion {
            get {
                return ResourceManager.GetString("UploadNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User info details.
        /// </summary>
        public static string UserInfoDetails {
            get {
                return ResourceManager.GetString("UserInfoDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users list.
        /// </summary>
        public static string UsersList {
            get {
                return ResourceManager.GetString("UsersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View and print report.
        /// </summary>
        public static string ViewAndPrintReport {
            get {
                return ResourceManager.GetString("ViewAndPrintReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit price.
        /// </summary>
        public static string VisitPrice {
            get {
                return ResourceManager.GetString("VisitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit statistics.
        /// </summary>
        public static string VisitStatistics {
            get {
                return ResourceManager.GetString("VisitStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without limitation.
        /// </summary>
        public static string WithoutLimitation {
            get {
                return ResourceManager.GetString("WithoutLimitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working hours.
        /// </summary>
        public static string WorkingHours {
            get {
                return ResourceManager.GetString("WorkingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can manage these clinics.
        /// </summary>
        public static string YouCanManageThisClinics {
            get {
                return ResourceManager.GetString("YouCanManageThisClinics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can manage these polyclinics.
        /// </summary>
        public static string YouCanManageThisPolyClinics {
            get {
                return ResourceManager.GetString("YouCanManageThisPolyClinics", resourceCulture);
            }
        }
    }
}
